### PR TITLE
signup feature

### PR DESCRIPTION
**Pull request by doktaslim**

### CODE REVIEW

**Comment by EphraimDev** [comment]
Can you post a picture of the page?

**Comment by doktaslim** [comment]
This is the screenshot

**Comment by EphraimDev** [comment]
Screenshot of the sign up page

**Comment by doktaslim** [comment]
I sent it earlier

**Comment by doktaslim** [comment]
Screenshot (131)

**Comment by EphraimDev** [comment]
For smaller screen sizes too

**Comment by doktaslim** [comment]
Screenshot (136)

**Pull request merged**
